FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
# Borramos el de fábrica por si acaso
RUN rm /etc/nginx/conf.d/default.conf
# Copiamos el nuestro (que ahora está en la raíz según el paso anterior)
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]