FROM node:18-alpine
WORKDIR /app

# Copiamos desde la carpeta backend que está en el mismo nivel que este Dockerfile
COPY backend/package*.json ./

RUN npm install

# Copiamos el resto del código de la carpeta backend
COPY backend/ .

EXPOSE 3001
# Asegúrate de que en tu package.json exista el script "start"
CMD ["npm", "start"]